name: Production deployment

on: [push]
  # push:
    # tags: [ "*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Set secret
      run: echo "${{secrets.DEPLOYER_PRIVATE_KEY}}" >> storages/deploy.pem
    - name: Accessing secret
      run: cat storages/deploy.pem
