name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Halo, ini adalah laporan issue pertamamu. Terima kasih telah menggunakan repo kami."
        pr-message: "Wow keren, ini adalah kontribusi kode pertamamu di repo kami. Kami akan senang mereview PR kamu!"
